const pairMeasuredBracketSkus = new Set([
  "JP-TOP-BRACKET",
  "JP-SHELF-BRACKET",
  "JP-CABINET-BRACKET"
]);

const nestedFastenerParentSkus = new Set([
  "JP-TOP-BRACKET",
  "JP-MIDDLE-BRACKET",
  "JP-CABINET-BRACKET",
  "JP-HORIZONTAL-RAIL",
  "JP-CORNER-BRACKET"
]);

const depthSizedAccessorySkus = new Set([
  "JP-TOP-BRACKET",
  "JP-SHELF-BRACKET",
  "JP-CORNER-BRACKET"
]);

export const japaneseClosetBomCalculator = {
  addSystemBom({
    activeWalls,
    postHeight,
    productBySku,
    productByType,
    rules,
    config,
    bomMap,
    addBom
  }) {
    const cornerBracket = productBySku["JP-CORNER-BRACKET"];
    const cornerBracketQuantity = activeWalls.reduce(
      (quantity, wall) => quantity + (wall.length <= 3000 ? 2 : 4),
      0
    );
    if (cornerBracket?.sellable) {
      addBom(
        bomMap,
        this.withSelectedDepthSizeRule(cornerBracket, config.shelfDepth),
        cornerBracketQuantity,
        this.chooseColor(cornerBracket, config)
      );
    }

    const basePostProduct = productBySku["JP-POST"] || productByType.post;
    const postSku = postHeight === 2000
      ? "JP-POST-2000"
      : postHeight === 2400
        ? "JP-POST-2400"
        : "JP-POST";
    const postProduct = productBySku[postSku] || basePostProduct;
    const postQuantity = activeWalls.reduce((sum, wall) => sum + wall.postCount, 0);
    if (postProduct?.sellable) {
      addBom(
        bomMap,
        { ...postProduct, sizeRule: `${postHeight}mm` },
        postQuantity,
        this.chooseColor(postProduct, config)
      );
    }

    rules
      .filter((rule) => ruleMatchesParent(rule, basePostProduct, "post"))
      .forEach((rule) => {
        const required = productBySku[rule.childSku || rule.requiredSku];
        if (!required?.sellable) return;
        addBom(
          bomMap,
          required,
          rule.quantity * postQuantity,
          this.chooseColor(required, config),
          rule.note
        );
      });
  },

  getPlacementRuleItem({ required, rule, placement, config }) {
    const rawQuantity = rule.quantity * placement.quantity;
    const quantity = pairMeasuredBracketSkus.has(required.sku)
      ? rawQuantity / 2
      : rawQuantity;
    const groupedProduct = required.sku === "JP-SHELF-BRACKET" && rule.note === "柜体用"
      ? { ...required, bomGroup: "柜体系统" }
      : required;
    const unitAdjustedProduct = pairMeasuredBracketSkus.has(required.sku)
      ? { ...groupedProduct, unit: "对" }
      : groupedProduct;
    return {
      product: this.withSelectedDepthSizeRule(unitAdjustedProduct, config.shelfDepth),
      quantity,
      color: this.chooseColor(required, config),
      note: rule.note
    };
  },

  expandNestedRules({ bomMap, rules, productBySku, config, addBom }) {
    Array.from(bomMap.values())
      .filter((item) => nestedFastenerParentSkus.has(item.sku))
      .forEach((parentItem) => {
        rules
          .filter((rule) => rule.parentSku === parentItem.sku)
          .forEach((rule) => {
            const required = productBySku[rule.childSku || rule.requiredSku];
            if (!required?.sellable) return;
            addBom(
              bomMap,
              required,
              rule.quantity * parentItem.quantity,
              this.chooseColor(required, config),
              rule.note
            );
          });
      });
  },

  createAutoPlacements({ rawPlacements, activeWalls, postHeight, productByType }) {
    const placements = Array.isArray(rawPlacements) ? rawPlacements : [];
    const woodTopProduct = productByType.woodTop;
    if (!woodTopProduct?.autoGenerated) return placements;
    const existingKeys = new Set(placements
      .filter((placement) => (placement.componentType || placement.type) === "woodTop")
      .map((placement) => `${placement.wallId}:${Number(placement.bayIndex)}`));
    const autoPlacements = activeWalls.flatMap((wall) => wall.bays.map((bay) => {
      const key = `${wall.id}:${bay.bayIndex}`;
      if (existingKeys.has(key)) return null;
      return {
        id: `auto:woodTop:${wall.id}:${bay.bayIndex}`,
        wallId: wall.id,
        bayIndex: bay.bayIndex,
        componentType: "woodTop",
        heightFromFloor: postHeight,
        quantity: 1,
        autoGenerated: true,
        heightLocked: true
      };
    }).filter(Boolean));
    return [...placements, ...autoPlacements];
  },

  withSelectedDepthSizeRule(product, shelfDepth) {
    if (!depthSizedAccessorySkus.has(product.sku)) return product;
    return { ...product, sizeRule: `${Number(shelfDepth)}mm` };
  },

  chooseColor(product, config) {
    if (
      product.type === "post"
      || product.type === "singleRail"
      || product.type === "doubleRail"
      || product.material === "碳钢"
      || product.category?.includes("配件")
    ) {
      return config.frameColor;
    }
    if (
      product.type === "woodTop"
      || product.type === "woodShelf"
      || product.type === "cabinet"
    ) {
      return "Wood Brown";
    }
    return product.colorOptions?.[0] || "Default Material";
  }
};

function ruleMatchesParent(rule, product, fallbackType) {
  const parentSku = rule.parentSku || "";
  if (parentSku && product?.sku) return parentSku === product.sku;
  return rule.configType === fallbackType;
}
