export const wallMountedV2BomCalculator = {
  addSystemBom({
    activeWalls,
    productBySku,
    rules,
    settings,
    config,
    bomMap,
    addBom
  }) {
    const postProduct = productBySku["BG-001"];
    const systemContext = buildSystemContext(activeWalls, settings, config);
    const systemManagedChildSkus = new Set(
      rules
        .filter((rule) => normalize(rule.parentSku) === "system")
        .map((rule) => rule.childSku)
    );

    activeWalls.forEach((wall) => {
      const wallPostCount = Number(wall.postCount || wall.posts?.length || 0);
      if (postProduct?.sellable && wallPostCount > 0) {
        addBom(bomMap, postProduct, wallPostCount, this.chooseColor(postProduct, config));
      }
      if (postProduct) {
        (wall.posts || []).forEach((post, index) => {
          expandChildren({
            parent: postProduct,
            parentQuantity: 1,
            context: {
              ...systemContext,
              wallBayCount: wall.bayCount,
              totalPosts: wallPostCount,
              leftPostIndex: index,
              rightPostIndex: index
            },
            rules,
            productBySku,
            config,
            bomMap,
            addBom,
            chooseColor: this.chooseColor.bind(this),
            path: [],
            skipChildSkus: new Set(["BG-BACK", ...systemManagedChildSkus])
          });
        });
      }
    });

    rules
      .filter((rule) => normalize(rule.parentSku) === "system")
      .filter((rule) => conditionMatches(rule.condition, systemContext))
      .forEach((rule) => {
        const child = productBySku[rule.childSku];
        const quantity = evaluateQuantity(rule.quantity, systemContext);
        if (!child || quantity <= 0) return;
        if (child.sellable) {
          addBom(bomMap, child, quantity, this.chooseColor(child, config), rule.note);
        }
        expandChildren({
          parent: child,
          parentQuantity: quantity,
          context: systemContext,
          rules,
          productBySku,
          config,
          bomMap,
          addBom,
          chooseColor: this.chooseColor.bind(this),
          path: ["SYSTEM"]
        });
      });
  },

  addPlacementBom({
    placement,
    component,
    activeWalls,
    productBySku,
    rules,
    settings,
    config,
    bomMap,
    addBom
  }) {
    if (!component) return;
    const wall = activeWalls.find((item) => item.id === placement.wallId);
    const context = {
      ...settings,
      ...config,
      ...placement,
      wallBayCount: Number(wall?.bayCount || 0),
      totalPosts: Number(wall?.postCount || 0)
    };
    const quantity = Number(placement.quantity || 1);
    if (component.sellable) {
      addBom(
        bomMap,
        { ...component, componentCutLength: placement.componentCutLength },
        quantity,
        this.chooseColor(component, config)
      );
    }
    expandChildren({
      parent: component,
      parentQuantity: quantity,
      context,
      rules,
      productBySku,
      config,
      bomMap,
      addBom,
      chooseColor: this.chooseColor.bind(this),
      path: []
    });
  },

  createAutoPlacements({ rawPlacements, activeWalls, productByType }) {
    const placements = Array.isArray(rawPlacements) ? [...rawPlacements] : [];
    const backPanel = productByType.backPanel;
    if (!backPanel) return placements;
    const existingIds = new Set(placements.map((placement) => placement.id));
    activeWalls.forEach((wall) => wall.bays.forEach((bay) => {
      const id = `auto:backPanel:${wall.id}:${bay.bayIndex}`;
      if (existingIds.has(id)) return;
      placements.push({
        id,
        wallId: wall.id,
        bayIndex: bay.bayIndex,
        componentType: "backPanel",
        productSku: backPanel.sku,
        heightFromFloor: 0,
        quantity: 1,
        autoGenerated: true,
        heightLocked: true
      });
      existingIds.add(id);
    }));
    return placements;
  },

  resolvePlacementProduct({ placement, productsByType, productByType, config }) {
    if (placement.productSku) {
      const exact = (productsByType[placement.componentType] || [])
        .find((product) => product.sku === placement.productSku);
      if (exact) return exact;
    }
    const candidates = productsByType[placement.componentType] || [];
    const requestedWidth = Number(placement.moduleWidth || placement.standardWidth);
    const requestedDepth = Number(config?.shelfDepth);
    return candidates.find((product) => product.widthOptions?.includes(requestedWidth))
      || candidates.find((product) => Number(product.depthRule) === requestedDepth)
      || productByType[placement.componentType];
  },

  ruleMatches(rule, settings, config, placement) {
    return conditionMatches(rule.condition, { ...settings, ...config, ...placement });
  },

  expandNestedRules() {},

  chooseColor(product, config) {
    if (["post", "singleRail"].includes(product.type)) {
      return config.frameColor || "Black";
    }
    if (["woodShelf", "shoeShelf", "cabinet", "backPanel"].includes(product.type)) {
      return config.panelColor || "Wood Brown";
    }
    return product.colorOptions?.[0] || "Default Material";
  }
};

function expandChildren({
  parent,
  parentQuantity,
  context,
  rules,
  productBySku,
  config,
  bomMap,
  addBom,
  chooseColor,
  path,
  skipChildSkus = new Set()
}) {
  if (!parent || path.includes(parent.sku)) return;
  const nextPath = [...path, parent.sku];
  rules
    .filter((rule) => rule.parentSku === parent.sku)
    .filter((rule) => !skipChildSkus.has(rule.childSku))
    .filter((rule) => conditionMatches(rule.condition, context))
    .forEach((rule) => {
      const child = productBySku[rule.childSku];
      if (!child) return;
      const factor = evaluateQuantity(rule.quantity, context);
      const quantity = factor * parentQuantity;
      if (!Number.isFinite(quantity) || quantity <= 0) return;
      if (child.sellable) {
        addBom(bomMap, child, quantity, chooseColor(child, config), rule.note);
      }
      expandChildren({
        parent: child,
        parentQuantity: quantity,
        context,
        rules,
        productBySku,
        config,
        bomMap,
        addBom,
        chooseColor,
        path: nextPath,
        skipChildSkus
      });
    });
}

function buildSystemContext(activeWalls, settings, config) {
  return {
    ...settings,
    ...config,
    wallBayCount: activeWalls.reduce((sum, wall) => sum + Number(wall.bayCount || 0), 0),
    totalPosts: activeWalls.reduce((sum, wall) => sum + Number(wall.postCount || 0), 0)
  };
}

function conditionMatches(condition, context) {
  const expression = String(condition || "").trim();
  if (!expression || normalize(expression) === "always") return true;
  const match = expression.match(/^([A-Za-z_][A-Za-z0-9_-]*)\s*(==|!=|>=|<=|=|>|<)\s*(.*?)$/);
  if (!match) return false;
  const [, key, operator, rawExpected] = match;
  const actual = context[key];
  if (actual === undefined) return false;
  const expected = rawExpected.trim().replace(/^(['"])(.*)\1$/, "$2");
  const numeric = isNumeric(actual) && isNumeric(expected);
  const left = numeric
    ? Number(actual)
    : normalize(key) === "layout"
      ? normalizeLayout(actual)
      : normalize(actual);
  const right = numeric
    ? Number(expected)
    : normalize(key) === "layout"
      ? normalizeLayout(expected)
      : normalize(expected);
  if (operator === "=" || operator === "==") return left === right;
  if (operator === "!=") return left !== right;
  if (operator === ">") return left > right;
  if (operator === ">=") return left >= right;
  if (operator === "<") return left < right;
  if (operator === "<=") return left <= right;
  return false;
}

function evaluateQuantity(quantity, context) {
  if (typeof quantity === "number") return quantity;
  const expression = String(quantity || "").trim();
  if (isNumeric(expression)) return Number(expression);
  return Number(context[expression]);
}

function normalize(value) {
  return String(value ?? "").trim().toLowerCase();
}

function normalizeLayout(value) {
  const layout = normalize(value);
  if (layout.startsWith("l")) return "l";
  if (layout.startsWith("u")) return "u";
  if (layout.startsWith("i")) return "i";
  return layout;
}

function isNumeric(value) {
  return value !== "" && Number.isFinite(Number(value));
}
