const typeAliases = {
  back: "backPanel",
  rail: "singleRail"
};

export const wallMountedV2SeriesConfig = {
  seriesId: "wall-mounted-v2",
  name: "壁挂式衣帽间",
  enabled: true,
  productsPath: "products/Wall-Mounted/Wall-Mounted.xlsx",
  rulesPath: "products/Wall-Mounted/Wall-Mounted.xlsx",
  brandPath: "brand/brand.json",
  logoPath: "brand/logo.png",
  clientBrandPath: "brand/client/brand.json",
  clientLogoPath: "brand/client-logo.png",
  assetRoot: "products/Wall-Mounted",
  imagePath: "products/Wall-Mounted/images",
  modelPath: "products/Wall-Mounted/models",
  suSourcePath: "",
  supportsLibraryClick: true,
  supportsPlacementBayControls: true,
  supportsLed: true,
  usesProductPostHeight: true,
  fixedFrameColor: "Black",
  fixedConfigColor: "black",

  resolvePostHeight({ productByType }) {
    const height = Number(productByType.post?.heightRule);
    return Number.isFinite(height) && height > 0 ? height : null;
  },

  normalizeProduct(product) {
    const sku = String(product.sku || "").trim();
    const rawType = String(product.type || "").trim();
    const isShoeShelf = /^BG-SHOE-SHELF-/.test(sku);
    const type = /^BG-008-3-/.test(sku)
      ? "jewelryBoxThreeDrawer"
      : /^BG-008-4-/.test(sku)
        ? "trouserRackThreeDrawer"
        : isShoeShelf
          ? "shoeShelf"
          : rawType === "shelf"
            ? "woodShelf"
            : typeAliases[rawType] || rawType;
    const width = Number(product.widthRule);
    const modelPath = String(product.modelPath || "").trim();
    const image = normalizeWallMountedImagePath(product.image);
    const hasModel = /\.(glb|gltf)$/i.test(modelPath);
    return {
      ...product,
      sku,
      nameCn: String(product.nameCn || "").trim(),
      nameEn: String(product.nameEn || "").trim(),
      type,
      category: String(product.category || "").trim(),
      modelPath: hasModel ? modelPath : "",
      glbAssetPath: hasModel ? modelPath : "",
      image,
      icon: String(product.icon || "").trim(),
      widthRule: String(product.widthRule || "").trim(),
      depthRule: String(product.depthRule || "").trim(),
      widthOptions: Number.isFinite(width) && width > 0 ? [width] : product.widthOptions,
      autoGenerated: type === "backPanel" || product.autoGenerated
    };
  },

  normalizeRule(rule) {
    return {
      ...rule,
      parentSku: String(rule.parentSku || "").trim(),
      childSku: String(rule.childSku || "").trim(),
      condition: String(rule.condition || "").trim() || "always",
      placement: String(rule.placement || "").trim(),
      heightRule: String(rule.heightRule || "").trim(),
      dedupeKey: String(rule.dedupeKey || "").trim()
    };
  },

  normalizeSettings(settings) {
    const wallOffsetOptions = splitOptions(
      settings.wallOffsetOptions || settings.optionWallOffset
    );
    return {
      ...settings,
      wallOffsetOptions: wallOffsetOptions.length ? wallOffsetOptions : [300, 400, 500],
      defaultWallOffset: positiveNumber(settings.defaultWallOffset, 400),
      fixedPostWallOffset: positiveNumber(settings.fixedPostWallOffset, 400),
      roomHeightFixed: 2700,
      postHeightOptions: [2700],
      defaultPostHeight: 2700,
      hideRoomHeightInput: true,
      shelfDepthOptions: [300, 450, 500],
      defaultShelfDepth: 450,
      defaultLed: parseBoolean(settings.defaultLed)
    };
  }
};

function splitOptions(value) {
  return String(value || "")
    .split(/[|/,，、\s]+/)
    .map(Number)
    .filter((item) => Number.isFinite(item) && item > 0);
}

function positiveNumber(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function parseBoolean(value) {
  return ["true", "1", "yes", "on"].includes(String(value || "").trim().toLowerCase());
}

function normalizeWallMountedImagePath(value) {
  const image = String(value || "").trim().replace(/\\/g, "/");
  return image === "images/BG-WOOD-SHELFpng"
    ? "images/BG-WOOD-SHELF.png"
    : image;
}
