export const DIRECT_DRAG_INTENT_THRESHOLD_PX = 8;

export const DIRECT_DRAG_SUPPORTED_SERIES = new Set([
  "japanese-closet",
  "aluminum-post-wardrobe",
  "carbon-steel-post-wardrobe-v2"
]);

export const DIRECT_DRAGGABLE_COMPONENT_TYPES = new Set([
  "woodShelf",
  "glassShelf",
  "shoeShelf",
  "shoesShelf",
  "singleRail",
  "doubleRail",
  "trouserRack",
  "jewelryBox",
  "drawerSingle",
  "drawerDouble",
  "mirror",
  "clothBoard",
  "cabinet",
  "storageBasket",
  "basket",
  "mixedStorage"
]);

const DRAWER_COMPONENT_TYPES = new Set(["drawerSingle", "drawerDouble"]);
const DRAWER_ERGONOMIC_HEIGHTS = Object.freeze([1100, 1050, 1150, 1000, 1200, 950, 1250, 900, 1300]);
const RAIL_COMPONENT_TYPES = new Set(["singleRail", "doubleRail"]);
const SHORT_HANG_CLEARANCE_MM = 700;
const COLLISION_CLEARANCE_MM = 20;

export function isDirectPlacementDragEnabled(series) {
  return DIRECT_DRAG_SUPPORTED_SERIES.has(series?.seriesId || "");
}

export function isDirectPlacementDraggable(placement, series) {
  if (!isDirectPlacementDragEnabled(series)) return false;
  if (!placement || !DIRECT_DRAGGABLE_COMPONENT_TYPES.has(placement.componentType)) return false;
  if (placement.autoGenerated || placement.heightLocked || placement.locked || placement.isVisualAsset) return false;
  if (placement.componentType === "woodTop" || placement.componentType === "post" || placement.componentType === "backPanel") return false;
  return true;
}

export function resolveDirectDragHeight({ placement, rawHeight, design }) {
  const candidates = getDirectDragHeightCandidates(placement, design);
  if (!candidates.length) return invalid("noLegalHeight");
  const nearest = candidates.reduce((best, candidate) => (
    Math.abs(candidate - rawHeight) < Math.abs(best - rawHeight) ? candidate : best
  ), candidates[0]);
  const patched = { ...placement, heightFromFloor: nearest };
  const validation = validateDirectPlacementPatch({
    placement: patched,
    design,
    targetWallId: patched.wallId,
    targetBayIndex: patched.bayIndex
  });
  return validation.valid ? { valid: true, heightFromFloor: nearest } : validation;
}

export function validateDirectPlacementPatch({ placement, design, targetWallId, targetBayIndex }) {
  const wall = (design?.activeWalls || []).find((item) => item.id === targetWallId);
  if (!wall) return invalid("invalidWall");
  const bayIndex = Number(targetBayIndex);
  if (!Number.isInteger(bayIndex) || bayIndex < 0 || bayIndex >= Number(wall.bayCount || 0)) {
    return invalid("invalidBay");
  }
  const candidate = {
    ...placement,
    wallId: targetWallId,
    bayIndex
  };
  if (DRAWER_COMPONENT_TYPES.has(candidate.componentType) && isPrimaryLongHangBay(candidate, design)) {
    return invalid("primaryLongHangBay");
  }
  const interval = getDirectPlacementInterval(candidate, design);
  if (!interval) return invalid("invalidHeight");
  const sameBayPlacements = (design?.placements || []).filter((item) => (
    item.id !== candidate.id
    && item.componentType
    && item.wallId === targetWallId
    && Number(item.bayIndex) === bayIndex
  ));
  if (sameBayPlacements.some((item) => {
    const other = getDirectPlacementInterval(item, design);
    return other && intervalsOverlap(interval, other);
  })) {
    return invalid("componentCollision");
  }
  if (DRAWER_COMPONENT_TYPES.has(candidate.componentType)
    && !hasDrawerHangingClearance(candidate, sameBayPlacements, design)) {
    return invalid("hangingClearanceBlocked");
  }
  return { valid: true };
}

export function getBayDragLabel(wallId, bayIndex) {
  return `${getWallLabel(wallId)} 第 ${Number(bayIndex) + 1} 跨`;
}

function getDirectDragHeightCandidates(placement, design) {
  const roomHeight = Math.max(0, Number(design?.room?.height) || 0);
  const componentType = placement.componentType;
  if (DRAWER_COMPONENT_TYPES.has(componentType)) {
    return filterCandidateHeights(DRAWER_ERGONOMIC_HEIGHTS, placement, design);
  }
  if (componentType === "trouserRack") {
    return filterCandidateHeights([900, 950, 1050, 1100, 1200, 1300], placement, design);
  }
  if (RAIL_COMPONENT_TYPES.has(componentType)) {
    return filterCandidateHeights([900, 1050, 1100, 1200, 1450, 1600, 1800, 2000, 2100], placement, design);
  }
  const step = ["woodShelf", "glassShelf", "shoeShelf", "shoesShelf"].includes(componentType) ? 50 : 100;
  const heights = [];
  for (let height = 0; height <= roomHeight; height += step) heights.push(height);
  return filterCandidateHeights(uniqueNumbers([Number(placement.heightFromFloor) || 0, ...heights]), placement, design);
}

function filterCandidateHeights(heights, placement, design) {
  return uniqueNumbers(heights)
    .filter((height) => Number.isFinite(height))
    .filter((height) => validateDirectPlacementPatch({
      placement: { ...placement, heightFromFloor: height },
      design,
      targetWallId: placement.wallId,
      targetBayIndex: placement.bayIndex
    }).valid);
}

function isPrimaryLongHangBay(candidate, design) {
  const sameBayPlacements = (design?.placements || []).filter((item) => (
    item.id !== candidate.id
    && item.componentType
    && item.wallId === candidate.wallId
    && Number(item.bayIndex) === Number(candidate.bayIndex)
  ));
  const hasHighRail = sameBayPlacements.some((item) => (
    RAIL_COMPONENT_TYPES.has(item.componentType)
    && Number(item.heightFromFloor || 0) >= 1800
  ));
  const hasStorageSurface = sameBayPlacements.some((item) => (
    ["woodShelf", "glassShelf", "shoeShelf", "shoesShelf", "cabinet", "jewelryBox", "trouserRack"].includes(item.componentType)
  ));
  return hasHighRail && !hasStorageSurface;
}

function hasDrawerHangingClearance(candidate, sameBayPlacements, design) {
  const drawerTop = getDirectPlacementInterval(candidate, design)?.top;
  if (!Number.isFinite(drawerTop)) return false;
  return sameBayPlacements.every((item) => {
    if (!RAIL_COMPONENT_TYPES.has(item.componentType)) return true;
    const railHeight = Number(item.heightFromFloor || 0);
    if (railHeight < 1800) return true;
    return railHeight - drawerTop >= SHORT_HANG_CLEARANCE_MM;
  });
}

function getDirectPlacementInterval(placement, design) {
  const heightFromFloor = Number(placement.heightFromFloor || 0);
  const componentHeight = getDirectPlacementComponentHeight(placement, design);
  if (!Number.isFinite(heightFromFloor) || !Number.isFinite(componentHeight) || componentHeight <= 0) return null;
  const rail = RAIL_COMPONENT_TYPES.has(placement.componentType);
  const bottom = rail ? heightFromFloor - componentHeight / 2 : heightFromFloor;
  const top = rail ? heightFromFloor + componentHeight / 2 : heightFromFloor + componentHeight;
  const roomHeight = Number(design?.room?.height) || 0;
  if (bottom < 0 || (roomHeight > 0 && top > roomHeight)) return null;
  return { bottom, top };
}

function getDirectPlacementComponentHeight(placement, design) {
  const product = design?.productBySku?.[placement.productSku] || design?.productByType?.[placement.componentType];
  const productHeight = Number(product?.heightRule ?? product?.height);
  if (Number.isFinite(productHeight) && productHeight > 0) return productHeight;
  return {
    singleRail: 50,
    doubleRail: 80,
    woodShelf: 40,
    glassShelf: 40,
    shoeShelf: 40,
    shoesShelf: 40,
    cabinet: 600,
    jewelryBox: 180,
    trouserRack: 180,
    drawerSingle: 180,
    drawerDouble: 360,
    mirror: 900,
    clothBoard: 820,
    storageBasket: 180,
    basket: 180,
    mixedStorage: 500
  }[placement.componentType] || 100;
}

function intervalsOverlap(left, right) {
  return left.bottom < right.top + COLLISION_CLEARANCE_MM
    && left.top > right.bottom - COLLISION_CLEARANCE_MM;
}

function invalid(reason) {
  return { valid: false, reason };
}

function uniqueNumbers(values) {
  return [...new Set(values.map(Number).filter(Number.isFinite))].sort((left, right) => left - right);
}

function getWallLabel(wallId) {
  if (wallId === "left") return "左墙";
  if (wallId === "right") return "右墙";
  return "背墙";
}
