export const aluminumBaseSupportedBomCalculator = {
  addSystemBom({
    activeWalls,
    productBySku,
    productByType,
    rules,
    settings,
    config,
    bomMap,
    addBom
  }) {
    const middlePost = productBySku["TD-001-1"] || productByType.post;
    const sidePost = productBySku["TD-001-2"];
    if (!middlePost) return;
    const postCounts = activeWalls.reduce((counts, wall) => {
      const wallPostCount = Number(wall.postCount || wall.posts?.length || 0);
      counts.side += Math.min(2, wallPostCount);
      counts.middle += Math.max(0, wallPostCount - 2);
      return counts;
    }, { side: 0, middle: 0 });
    const postQuantity = postCounts.side + postCounts.middle;
    if (middlePost.sellable && postCounts.middle > 0) {
      addBom(bomMap, middlePost, postCounts.middle, this.chooseColor(middlePost, config));
    }
    if (sidePost?.sellable && postCounts.side > 0) {
      addBom(bomMap, sidePost, postCounts.side, this.chooseColor(sidePost, config));
    }

    expandChildren({
      parent: middlePost,
      parentQuantity: postQuantity,
      context: buildSystemContext(activeWalls, settings, config),
      rules,
      productBySku,
      config,
      bomMap,
      addBom,
      chooseColor: this.chooseColor.bind(this),
      path: []
    });

    rules
      .filter((rule) => normalize(rule.parentSku) === "system")
      .filter((rule) => conditionMatches(rule.condition, buildSystemContext(activeWalls, settings, config)))
      .forEach((rule) => {
        const child = productBySku[rule.childSku];
        const quantity = evaluateQuantity(rule.quantity, buildSystemContext(activeWalls, settings, config));
        if (child?.sellable && quantity > 0) {
          addBom(bomMap, child, quantity, this.chooseColor(child, config), rule.note);
        }
      });
  },

  addPlacementBom({
    placement,
    component,
    activeWalls,
    productBySku,
    rules,
    settings,
    config,
    bomMap,
    addBom
  }) {
    if (!component) return;
    const wall = activeWalls.find((item) => item.id === placement.wallId);
    const context = {
      ...settings,
      ...config,
      ...placement,
      leftPostIndex: Number(placement.bayIndex),
      rightPostIndex: Number(placement.bayIndex) + 1,
      totalPosts: Number(wall?.postCount || 0),
      wallBayCount: Number(wall?.bayCount || 0)
    };
    const quantity = Number(placement.quantity || 1);
    if (component.sellable) {
      addBom(bomMap, component, quantity, this.chooseColor(component, config));
    }
    expandChildren({
      parent: component,
      parentQuantity: quantity,
      context,
      rules,
      productBySku,
      config,
      bomMap,
      addBom,
      chooseColor: this.chooseColor.bind(this),
      path: [],
      skipPlacementRules: true
    });
  },

  createAutoPlacements({
    rawPlacements,
    activeWalls,
    productBySku,
    productByType,
    rules,
    config
  }) {
    const placements = Array.isArray(rawPlacements) ? [...rawPlacements] : [];
    const existingIds = new Set(placements.map((placement) => placement.id));
    const backPanel = productByType.backPanel;
    if (backPanel) {
      activeWalls.forEach((wall) => wall.bays.forEach((bay) => {
        const id = `auto:backPanel:${wall.id}:${bay.bayIndex}`;
        if (existingIds.has(id)) return;
        placements.push({
          id,
          wallId: wall.id,
          bayIndex: bay.bayIndex,
          componentType: backPanel.type,
          heightFromFloor: 0,
          quantity: 1,
          autoGenerated: true,
          heightLocked: true
        });
        existingIds.add(id);
      }));
    }

    const sourcePlacements = placements.filter((placement) => !placement.autoGenerated);
    const wallWideShelfRowKeys = new Set();
    sourcePlacements.forEach((placement) => {
      const parent = resolvePlacementProduct(placement, productBySku, productByType);
      if (!isWallWideProduct(parent)) return;
      const wall = activeWalls.find((item) => item.id === placement.wallId);
      if (!wall) return;
      const sourcePlacement = {
        ...placement,
        wallWideSource: true
      };
      placements[placements.indexOf(placement)] = sourcePlacement;
      wallWideShelfRowKeys.add(getWallWideShelfRowKey(
        placement.wallId,
        placement.heightFromFloor
      ));

      wall.bays.forEach((bay) => {
        if (bay.bayIndex === Number(placement.bayIndex)) return;
        const id = `auto:wallWide:${placement.id}:${placement.wallId}:${bay.bayIndex}`;
        if (existingIds.has(id)) return;
        placements.push({
          ...sourcePlacement,
          id,
          wallId: placement.wallId,
          bayIndex: bay.bayIndex,
          autoGenerated: true,
          sourcePlacementId: placement.id,
          wallWideDerived: true
        });
        existingIds.add(id);
      });
    });

    const placementRuleSources = placements.filter((placement) => (
      !placement.autoGenerated || placement.wallWideDerived
    ));
    placementRuleSources.forEach((placement) => {
      const parent = resolvePlacementProduct(placement, productBySku, productByType);
      rules
        .filter((rule) => rule.parentSku === parent?.sku && rule.placement)
        .filter((rule) => conditionMatches(rule.condition, { ...config, ...placement }))
        .forEach((rule) => {
          const child = productBySku[rule.childSku];
          if (!child) return;
          const heightFromFloor = rule.heightRule === "aboveParent"
            ? Number(placement.heightFromFloor || 0) + 300
            : Number(placement.heightFromFloor || 0);
          if (isLinkedWallWideShelfRule(parent, child)) {
            const wall = activeWalls.find((item) => item.id === placement.wallId);
            const rowKey = getWallWideShelfRowKey(placement.wallId, heightFromFloor);
            if (!wall || wallWideShelfRowKeys.has(rowKey)) return;
            wallWideShelfRowKeys.add(rowKey);
            wall.bays.forEach((bay) => {
              const id = `auto:wallWideLinked:${placement.id}:${placement.wallId}:${bay.bayIndex}`;
              if (existingIds.has(id)) return;
              placements.push({
                id,
                wallId: placement.wallId,
                bayIndex: bay.bayIndex,
                componentType: child.type,
                productSku: child.sku,
                heightFromFloor,
                quantity: evaluateQuantity(rule.quantity, { ...config, ...placement }) || 1,
                autoGenerated: true,
                heightLocked: true,
                sourcePlacementId: placement.id,
                wallWideDerived: true,
                linkedWallWideShelf: true
              });
              existingIds.add(id);
            });
            return;
          }
          const id = `auto:${rule.dedupeKey || rule.childSku}:${placement.wallId}:${placement.bayIndex}`;
          if (existingIds.has(id)) return;
          placements.push({
            id,
            wallId: placement.wallId,
            bayIndex: placement.bayIndex,
            componentType: child.type,
            heightFromFloor,
            quantity: evaluateQuantity(rule.quantity, { ...config, ...placement }) || 1,
            autoGenerated: true,
            heightLocked: true
          });
          existingIds.add(id);
        });
    });
    return placements;
  },

  resolvePlacementProduct({ placement, productsByType, productByType }) {
    const candidates = productsByType[placement.componentType] || [];
    const requestedWidth = Number(placement.moduleWidth || placement.standardWidth);
    return candidates.find((product) => product.widthOptions?.includes(requestedWidth))
      || productByType[placement.componentType];
  },

  ruleMatches(rule, settings, config, placement) {
    return conditionMatches(rule.condition, { ...settings, ...config, ...placement });
  },

  getPlacementRuleItem({ required, rule, placement, config }) {
    return {
      product: required,
      quantity: evaluateQuantity(rule.quantity, { ...config, ...placement }) * placement.quantity,
      color: this.chooseColor(required, config),
      note: rule.note
    };
  },

  expandNestedRules() {},

  chooseColor(product, config) {
    const options = product.colorOptions || [];
    if (options.includes("inheritPostColor") || options.includes("black")) {
      return config.frameColor || "Black";
    }
    if (options.includes("woodBrown")) return config.panelColor || "Wood Brown";
    if (options.includes("clearGlass")) return config.glassColor || "透明灰";
    return options[0] || "Default Material";
  }
};

function expandChildren({
  parent,
  parentQuantity,
  context,
  rules,
  productBySku,
  config,
  bomMap,
  addBom,
  chooseColor,
  path,
  skipPlacementRules = false
}) {
  if (!parent || path.includes(parent.sku)) return;
  const nextPath = [...path, parent.sku];
  rules
    .filter((rule) => rule.parentSku === parent.sku)
    .filter((rule) => !(skipPlacementRules && rule.placement))
    .filter((rule) => conditionMatches(rule.condition, context))
    .forEach((rule) => {
      const child = productBySku[rule.childSku];
      if (!child) return;
      const factor = evaluateQuantity(rule.quantity, context);
      const quantity = isGlobalQuantity(rule.quantity)
        ? factor
        : factor * parentQuantity;
      if (!Number.isFinite(quantity) || quantity <= 0) return;
      if (child.sellable) {
        addBom(bomMap, child, quantity, chooseColor(child, config), rule.note);
      }
      expandChildren({
        parent: child,
        parentQuantity: quantity,
        context,
        rules,
        productBySku,
        config,
        bomMap,
        addBom,
        chooseColor,
        path: nextPath,
        skipPlacementRules
      });
    });
}

function resolvePlacementProduct(placement, productBySku, productByType) {
  return productBySku[placement.productSku] || productByType[placement.componentType];
}

function isWallWideProduct(product) {
  return String(product?.sku || "") === "TD-WOOD-SHELF";
}

function isLinkedWallWideShelfRule(parent, child) {
  const parentSku = String(parent?.sku || "");
  return (parentSku === "TD-CABINET" || /^TD-007-[234]-/.test(parentSku))
    && String(child?.sku || "") === "TD-WOOD-SHELF";
}

function getWallWideShelfRowKey(wallId, heightFromFloor) {
  return `${wallId}:${Number(heightFromFloor || 0)}`;
}

function buildSystemContext(activeWalls, settings, config) {
  return {
    ...settings,
    ...config,
    wallBayCount: activeWalls.reduce((sum, wall) => sum + Number(wall.bayCount || 0), 0),
    totalPosts: activeWalls.reduce((sum, wall) => sum + Number(wall.postCount || 0), 0)
  };
}

function conditionMatches(condition, context) {
  const expression = String(condition || "").trim();
  if (!expression || normalize(expression) === "always") return true;
  const match = expression.match(/^([A-Za-z_][A-Za-z0-9_-]*)\s*(==|!=|>=|<=|=|>|<)\s*(.*?)$/);
  if (!match) return false;
  const [, key, operator, rawExpected] = match;
  const actual = context[key];
  if (actual === undefined) return false;
  const expected = rawExpected.trim().replace(/^(['"])(.*)\1$/, "$2");
  const numeric = isNumeric(actual) && isNumeric(expected);
  const left = numeric ? Number(actual) : normalize(actual);
  const right = numeric ? Number(expected) : normalize(expected);
  if (operator === "=" || operator === "==") return left === right;
  if (operator === "!=") return left !== right;
  if (operator === ">") return left > right;
  if (operator === ">=") return left >= right;
  if (operator === "<") return left < right;
  if (operator === "<=") return left <= right;
  return false;
}

function evaluateQuantity(quantity, context) {
  if (typeof quantity === "number") return quantity;
  const expression = String(quantity || "").trim();
  if (isNumeric(expression)) return Number(expression);
  return Number(context[expression]);
}

function isGlobalQuantity(quantity) {
  return String(quantity || "").trim() === "wallBayCount";
}

function normalize(value) {
  return String(value ?? "").trim().toLowerCase();
}

function isNumeric(value) {
  return value !== "" && Number.isFinite(Number(value));
}
