import * as XLSX from "xlsx";

export const productFields = [
  "sku",
  "nameCn",
  "nameEn",
  "type",
  "category",
  "material",
  "colorOptions",
  "width",
  "depth",
  "height",
  "heightRule",
  "sizeRule",
  "unitPrice",
  "unit",
  "sellable",
  "image",
  "icon",
  "modelPath",
  "glbAssetPath",
  "skpComponentName",
  "bomGroup",
  "sortOrder",
  "resizeMode",
  "cuttable",
  "description",
  "autoGenerated",
  "heightLocked"
];

export const ruleFields = ["parentSku", "childSku", "quantity", "condition", "note"];

export async function loadWorkbookData(series) {
  const productsPath = series.productsPath || series.productPath;
  const rulesPath = series.rulesPath;
  const [productsResponse, rulesResponse] = await Promise.all([
    fetch(`/${productsPath}?v=${Date.now()}`, { cache: "no-store" }),
    fetch(`/${rulesPath}?v=${Date.now()}`, { cache: "no-store" })
  ]);

  if (!productsResponse.ok) throw new Error(`鏃犳硶璇诲彇 /${productsPath}`);
  if (!rulesResponse.ok) throw new Error(`鏃犳硶璇诲彇 /${rulesPath}`);

  const [productsBuffer, rulesBuffer] = await Promise.all([
    productsResponse.arrayBuffer(),
    rulesResponse.arrayBuffer()
  ]);

  const products = applySeriesProductNormalization(parseProductsWorkbook(productsBuffer), series);
  const rules = applySeriesRuleNormalization(parseRulesWorkbook(rulesBuffer), series);
  const settings = applySeriesSettingsNormalization(parseSettingsWorkbook(productsBuffer), series);
  const cuttingRules = parseFormulaSheet(productsBuffer, ["CuttingRules"], ["sku", "componentType"]);
  const layoutRules = parseFormulaSheet(productsBuffer, ["LayoutRules"], ["ruleKey"]);
  const projectConfig = parseKeyValueSheet(productsBuffer, ["ProjectConfig"], ["configKey", "key"]);
  return {
    products,
    rules,
    settings,
    cuttingRules,
    layoutRules,
    projectConfig,
    workbookStats: {
      productCount: products.length,
      ruleCount: rules.length,
      cuttingRuleCount: cuttingRules.length,
      settingCount: settings.__rawCount || 0
    },
    source: "xlsx",
    series
  };
}

export async function parseWorkbook(fileOrBuffer, series = null) {
  const buffer = fileOrBuffer instanceof ArrayBuffer ? fileOrBuffer : await fileOrBuffer.arrayBuffer();
  const workbook = XLSX.read(buffer, { type: "array" });
  const products = rowsFromWorkbook(workbook, ["Products", "Sheet1"]).map(normalizeProduct).filter((product) => product.sku);
  const rules = rowsFromWorkbook(workbook, ["Rules", "Sheet3"]).map(normalizeRule).filter((rule) => rule.parentSku && rule.childSku);
  return { products, rules, source: "localStorage", series };
}

export async function parseProductFile(fileOrBuffer, series = null) {
  const buffer = fileOrBuffer instanceof ArrayBuffer ? fileOrBuffer : await fileOrBuffer.arrayBuffer();
  return applySeriesProductNormalization(parseProductsWorkbook(buffer), series);
}

export async function parseRulesFile(fileOrBuffer, series = null) {
  const buffer = fileOrBuffer instanceof ArrayBuffer ? fileOrBuffer : await fileOrBuffer.arrayBuffer();
  return applySeriesRuleNormalization(parseRulesWorkbook(buffer), series);
}

export function saveWorkbookOverride(seriesId, data) {
  localStorage.setItem(storageKey(seriesId), JSON.stringify({ ...data, source: "localStorage" }));
}

export function clearWorkbookOverride(seriesId) {
  localStorage.removeItem(storageKey(seriesId));
}

export function exportProductsWorkbook(data) {
  const workbook = XLSX.utils.book_new();
  const rows = data.products.map(serializeProduct);
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), "Products");
  XLSX.writeFile(workbook, `${data.series.seriesId}-products.xlsx`);
}

export function exportRulesWorkbook(data) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(data.rules.map(serializeRule)), "Rules");
  XLSX.writeFile(workbook, `${data.series.seriesId}-rules.xlsx`);
}

export function exportWorkbook(data) {
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(data.products.map(serializeProduct)), "Products");
  XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(data.rules.map(serializeRule)), "Rules");
  XLSX.writeFile(workbook, `${data.series.seriesId}-workbook.xlsx`);
}

function parseProductsWorkbook(buffer) {
  const workbook = XLSX.read(buffer, { type: "array" });
  return rowsFromWorkbook(workbook, ["Products", "Sheet1"]).map(normalizeProduct).filter((product) => product.sku);
}

function parseRulesWorkbook(buffer) {
  const workbook = XLSX.read(buffer, { type: "array" });
  return rowsFromWorkbook(workbook, ["Rules", "Sheet3"]).map(normalizeRule).filter((rule) => rule.parentSku && rule.childSku);
}

function parseSettingsWorkbook(buffer) {
  const fallback = {
    defaultWallOffset: 450,
    wallOffsetOptions: [300, 450, 500],
    roomHeightFixed: 2700,
    postHeightOptions: [2000, 2400],
    defaultPostHeight: 2400,
    hideRoomHeightInput: true,
    shelfDepthOptions: [300, 450, 500],
    defaultShelfDepth: 450,
    fixedPostWallOffset: 250
  };
  try {
    const workbook = XLSX.read(buffer, { type: "array" });
    const rows = rowsFromWorkbook(workbook, ["Settings", "setting sheet"]);
    const rawSettings = Object.fromEntries(rows
      .map((row) => [String(row.key ?? row.Key ?? "").trim(), String(row.value ?? row.Value ?? "").trim()])
      .filter(([key]) => key));
    const options = splitOptions(rawSettings.wallOffsetOptions).map(Number).filter((value) => Number.isFinite(value) && value > 0);
    const defaultWallOffset = Number(rawSettings.defaultWallOffset);
    const roomHeightFixed = Number(rawSettings.roomHeightFixed);
    const postHeightOptions = splitOptions(rawSettings.postHeightOptions).map(Number).filter((value) => Number.isFinite(value) && value > 0);
    const defaultPostHeight = Number(rawSettings.defaultPostHeight);
    const shelfDepthOptions = splitOptions(rawSettings.shelfDepthOptions).map(Number).filter((value) => Number.isFinite(value) && value > 0);
    const defaultShelfDepth = Number(rawSettings.defaultShelfDepth);
    const fixedPostWallOffset = Number(rawSettings.fixedPostWallOffset);
    const connectionModeOptions = splitOptions(rawSettings.connectionModeOptions ?? rawSettings.connectionMode);
    const requestedConnectionMode = normalizeConnectionMode(rawSettings.defaultConnectionMode);
    return {
      ...rawSettings,
      defaultWallOffset: Number.isFinite(defaultWallOffset) && defaultWallOffset > 0 ? defaultWallOffset : fallback.defaultWallOffset,
      wallOffsetOptions: options.length ? options : fallback.wallOffsetOptions,
      roomHeightFixed: Number.isFinite(roomHeightFixed) && roomHeightFixed > 0 ? roomHeightFixed : fallback.roomHeightFixed,
      postHeightOptions: postHeightOptions.length ? postHeightOptions : fallback.postHeightOptions,
      defaultPostHeight: Number.isFinite(defaultPostHeight) && defaultPostHeight > 0 ? defaultPostHeight : fallback.defaultPostHeight,
      hideRoomHeightInput: rawSettings.hideRoomHeightInput === undefined ? fallback.hideRoomHeightInput : parseBool(rawSettings.hideRoomHeightInput),
      shelfDepthOptions: shelfDepthOptions.length ? shelfDepthOptions : fallback.shelfDepthOptions,
      defaultShelfDepth: Number.isFinite(defaultShelfDepth) && defaultShelfDepth > 0 ? defaultShelfDepth : fallback.defaultShelfDepth,
      fixedPostWallOffset: Number.isFinite(fixedPostWallOffset) && fixedPostWallOffset > 0 ? fixedPostWallOffset : fallback.fixedPostWallOffset,
      connectionModeOptions,
      defaultConnectionMode: connectionModeOptions.includes(requestedConnectionMode)
        ? requestedConnectionMode
        : connectionModeOptions[0] || requestedConnectionMode || "wall",
      __rawCount: Object.keys(rawSettings).length
    };
  } catch (error) {
    console.warn("Settings Sheet read failed, using fallback.", error);
    return fallback;
  }
}

function readStoredWorkbook(seriesId) {
  try {
    const raw = localStorage.getItem(storageKey(seriesId));
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed.products) || !Array.isArray(parsed.rules)) return null;
    return parsed;
  } catch {
    return null;
  }
}

function storageKey(seriesId) {
  return `omeixProductWorkbookOverride:${seriesId}`;
}

function rowsFromWorkbook(workbook, names) {
  const sheetName = names.find((name) => workbook.Sheets[name]) || workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];
  if (!sheet) return [];
  return XLSX.utils.sheet_to_json(sheet, { defval: "" });
}

function normalizeProduct(row) {
  const sku = String(row.sku ?? row.productId ?? row["浜у搧缂栧彿"] ?? "").trim();
  return {
    sku,
    nameCn: String(row.nameCn ?? row.name ?? row["鍚嶇О"] ?? "").trim(),
    nameEn: String(row.nameEn ?? ""),
    type: String(row.type ?? row["绫诲瀷"] ?? "").trim(),
    category: String(row.category ?? ""),
    material: String(row.material ?? row["鏉愯川"] ?? "").trim(),
    colorOptions: splitOptions(row.colorOptions ?? row.color ?? row["棰滆壊"]),
    widthRule: String(row.widthRule ?? row.WidthRule ?? "").trim(),
    widthOptions: splitOptions(row.widthOptions).map(Number).filter((value) => Number.isFinite(value) && value > 0),
    depthRule: String(row.depthRule ?? row.DepthRule ?? "").trim(),
    width: numberOrBlank(row.width),
    depth: numberOrBlank(row.depth),
    height: row.height === "" || row.height == null ? "" : String(row.height),
    heightRule: String(row.heightRule ?? row.HeightRule ?? "").trim(),
    sizeRule: String(
      row.sizeRule
      ?? [row.WidthRule, row.DepthRule].filter(Boolean).join(" ")
      ?? row["灏哄"]
      ?? ""
    ),
    unitPrice: numberOrZero(row.unitPrice ?? row["鍗曚环"]),
    unit: String(row.unit || "件"),
    sellable: parseBool(row.sellable ?? row["鏄惁鍞崠"]),
    image: String(row.image ?? row.imagePath ?? ""),
    icon: String(row.icon ?? ""),
    modelPath: String(row.modelPath ?? row.glbAssetPath ?? ""),
    glbAssetPath: String(row.glbAssetPath ?? row.modelPath ?? ""),
    skpComponentName: String(row.skpComponentName ?? row["su鍚嶅瓧"] ?? ""),
    bomGroup: String(row.bomGroup ?? row["BOM鍒嗙粍"] ?? row["bom鍒嗙粍"] ?? "").trim(),
    sortOrder: numberOrBlank(row.sortOrder ?? row["排序"] ?? row["排序号"]),
    resizeMode: String(row.resizeMode ?? "").trim(),
    cuttable: parseBool(row.cuttable ?? row["鏄惁鍓昂"]),
    description: String(row.description ?? ""),
    materialTexture: String(row.materialTexture ?? ""),
    autoGenerated: parseBool(row.autoGenerated),
    heightLocked: parseBool(row.heightLocked)
  };
}

function parseFormulaSheet(buffer, sheetNames, keyFields) {
  try {
    const workbook = XLSX.read(buffer, { type: "array" });
    return rowsFromWorkbook(workbook, sheetNames)
      .map((row) => {
        const key = keyFields.map((field) => row[field]).find((value) => String(value ?? "").trim());
        return {
          ...row,
          key: String(key ?? "").trim(),
          formula: String(row.formula ?? "").trim()
        };
      })
      .filter((row) => row.key && row.formula);
  } catch (error) {
    console.warn(`${sheetNames[0]} Sheet read failed.`, error);
    return [];
  }
}

function parseKeyValueSheet(buffer, sheetNames, keyFields) {
  try {
    const workbook = XLSX.read(buffer, { type: "array" });
    return Object.fromEntries(rowsFromWorkbook(workbook, sheetNames)
      .map((row) => {
        const key = keyFields.map((field) => row[field]).find((value) => String(value ?? "").trim());
        return [String(key ?? "").trim(), numberOrString(row.value)];
      })
      .filter(([key]) => key));
  } catch (error) {
    console.warn(`${sheetNames[0]} Sheet read failed.`, error);
    return {};
  }
}

function normalizeRule(row) {
  const parentSku = String(row.parentSku ?? row.configType ?? row["主产品"] ?? "").trim();
  const childSku = String(row.childSku ?? row.requiredSku ?? row["SKU"] ?? row["自动生成SKU"] ?? "").trim();
  const rawQuantity = row.quantity ?? row["数量"];
  const numericQuantity = Number(rawQuantity);
  return {
    parentSku,
    childSku,
    configType: parentSku,
    requiredSku: childSku,
    quantity: rawQuantity !== "" && Number.isFinite(numericQuantity)
      ? numericQuantity
      : String(rawQuantity ?? "").trim(),
    condition: String(row.condition ?? "").trim(),
    note: String(row.note ?? row["备注"] ?? ""),
    placement: String(row.placement ?? "").trim(),
    heightRule: String(row.heightRule ?? "").trim(),
    dedupeKey: String(row.dedupeKey ?? "").trim()
  };
}

function applySeriesProductNormalization(products, series) {
  if (typeof series?.normalizeProduct !== "function") return products;
  return products.map((product) => series.normalizeProduct(product));
}

function applySeriesRuleNormalization(rules, series) {
  if (typeof series?.normalizeRule !== "function") return rules;
  return rules.map((rule) => series.normalizeRule(rule));
}

function applySeriesSettingsNormalization(settings, series) {
  if (typeof series?.normalizeSettings !== "function") return settings;
  return series.normalizeSettings(settings);
}

function serializeProduct(product) {
  return {
    ...Object.fromEntries(productFields.map((field) => [field, product[field] ?? ""])),
    colorOptions: Array.isArray(product.colorOptions) ? product.colorOptions.join("|") : product.colorOptions,
    sellable: product.sellable ? "true" : "false"
  };
}

function serializeRule(rule) {
  return Object.fromEntries(ruleFields.map((field) => [field, rule[field] ?? ""]));
}

function parseBool(value) {
  const normalized = String(value ?? "").trim().toLowerCase();
  return value === true || value === 1 || ["true", "yes", "y", "是"].includes(normalized);
}

function splitOptions(value) {
  return String(value || "")
    .split(/[|,，、；;\/\\]/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function numberOrZero(value) {
  const parsed = Number(String(value || "0").replace(/[^\d.-].*$/, ""));
  return Number.isFinite(parsed) ? parsed : 0;
}

function numberOrBlank(value) {
  if (value === "" || value == null) return "";
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : "";
}

function numberOrString(value) {
  const parsed = Number(value);
  return value !== "" && Number.isFinite(parsed) ? parsed : String(value ?? "").trim();
}

function normalizeConnectionMode(value) {
  const normalized = String(value || "").trim().toLowerCase();
  return normalized === "celling" ? "ceiling" : normalized;
}
